use MiFarma;

INSERT INTO Pais(Pais) values
('Peru');

INSERT INTO Departamento (Departamento,id_pais)
VALUES
('Amazonas',1),
('Áncash',1),
('Apurímac',1),
('Arequipa',1),
('Ayacucho',1),
('Cajamarca',1),
('Callao',1),
('Cusco',1),
('Huancavelica',1),
('Huánuco',1),
('Ica',1),
('Junín',1),
('La Libertad',1),
('Lambayeque',1),
('Lima',1),
('Loreto',1),
('Madre de Dios',1),
('Moquegua',1),
('Pasco',1),
('Piura',1),
('Puno',1),
('San Martín',1),
('Tacna',1),
('Tumbes',1),
('Ucayali',1);

INSERT INTO Provincia (Provincia, id_departamento) VALUES
('Chachapoyas', 1),
('Bagua', 1),
('Bongará', 1),
('Condorcanqui', 1),
('Luya', 1),
('Rodríguez de Mendoza', 1),
('Utcubamba', 1),
('Huaraz', 2),
('Aija', 2),
('Antonio Raymondi', 2),
('Asunción', 2),
('Bolognesi', 2),
('Carhuaz', 2),
('Carlos Fermín Fitzcarrald', 2),
('Casma', 2),
('Corongo', 2),
('Huari', 2),
('Huarmey', 2),
('Huaylas', 2),
('Mariscal Luzuriaga', 2),
('Ocros', 2),
('Pallasca', 2),
('Pomabamba', 2),
('Recuay', 2),
('Santa', 2),
('Sihuas', 2),
('Yungay', 2),
('Abancay', 3),
('Andahuaylas', 3),
('Antabamba', 3),
('Aymaraes', 3),
('Cotabambas', 3),
('Chincheros', 3),
('Grau', 3),
('Arequipa', 4),
('Camaná', 4),
('Caravelí', 4),
('Castilla', 4),
('Caylloma', 4),
('Condesuyos', 4),
('Islay', 4),
('La Uniòn', 4),
('Huamanga', 5),
('Cangallo', 5),
('Huanca Sancos', 5),
('Huanta', 5),
('La Mar', 5),
('Lucanas', 5),
('Parinacochas', 5),
('Pàucar del Sara Sara', 5),
('Sucre', 5),
('Víctor Fajardo', 5),
('Vilcas Huamán', 5),
('Cajamarca', 6),
('Cajabamba', 6),
('Celendín', 6),
('Chota', 6),
('Contumazá', 6),
('Cutervo', 6),
('Hualgayoc', 6),
('Jaén', 6),
('San Ignacio', 6),
('San Marcos', 6),
('San Miguel', 6),
('San Pablo', 6),
('Santa Cruz', 6),
('Prov. Const. del Callao', 7),
('Cusco', 8),
('Acomayo', 8),
('Anta', 8),
('Calca', 8),
('Canas', 8),
('Canchis', 8),
('Chumbivilcas', 8),
('Espinar', 8),
('La Convención', 8),
('Paruro', 8),
('Paucartambo', 8),
('Quispicanchi', 8),
('Urubamba', 8),
('Huancavelica', 9),
('Acobamba', 9),
('Angaraes', 9),
('Castrovirreyna', 9),
('Churcampa', 9),
('Huaytará', 9),
('Tayacaja', 9),
('Huánuco', 10),
('Ambo', 10),
('Dos de Mayo', 10),
('Huacaybamba', 10),
('Huamalíes', 10),
('Leoncio Prado', 10),
('Marañón', 10),
('Pachitea', 10),
('Puerto Inca', 10),
('Lauricocha', 10),
('Yarowilca', 10),
('Ica', 11),
('Chincha', 11),
('Nasca', 11),
('Palpa', 11),
('Pisco', 11),
('Huancayo', 12),
('Concepción', 12),
('Chanchamayo', 12),
('Jauja', 12),
('Junín', 12),
('Satipo', 12),
('Tarma', 12),
('Yauli', 12),
('Chupaca', 12),
('Trujillo', 13),
('Ascope', 13),
('Bolívar', 13),
('Chepén', 13),
('Julcán', 13),
('Otuzco', 13),
('Pacasmayo', 13),
('Pataz', 13),
('Sánchez Carrión', 13),
('Santiago de Chuco', 13),
('Gran Chimú', 13),
('Virú', 13),
('Chiclayo', 14),
('Ferreñafe', 14),
('Lambayeque', 14),
('Lima', 15),
('Barranca', 15),
('Cajatambo', 15),
('Canta', 15),
('Cañete', 15),
('Huaral', 15),
('Huarochirí', 15),
('Huaura', 15),
('Oyón', 15),
('Yauyos', 15),
('Maynas', 16),
('Alto Amazonas', 16),
('Loreto', 16),
('Mariscal Ramón Castilla', 16),
('Requena', 16),
('Ucayali', 16),
('Datem del Marañón', 16),
('Putumayo', 16),
('Tambopata', 17),
('Manu', 17),
('Tahuamanu', 17),
('Mariscal Nieto', 18),
('General Sánchez Cerro', 18),
('Ilo', 18),
('Pasco', 19),
('Daniel Alcides Carrión', 19),
('Oxapampa', 19),
('Piura', 20),
('Ayabaca', 20),
('Huancabamba', 20),
('Morropón', 20),
('Paita', 20),
('Sullana', 20),
('Talara', 20),
('Sechura', 20),
('Puno', 21),
('Azángaro', 21),
('Carabaya', 21),
('Chucuito', 21),
('El Collao', 21),
('Huancané', 21),
('Lampa', 21),
('Melgar', 21),
('Moho', 21),
('San Antonio de Putina', 21),
('San Román', 21),
('Sandia', 21),
('Yunguyo', 21),
('Moyobamba', 22),
('Bellavista', 22),
('El Dorado', 22),
('Huallaga', 22),
('Lamas', 22),
('Mariscal Cáceres', 22),
('Picota', 22),
('Rioja', 22),
('San Martín', 22),
('Tocache', 22),
('Tacna', 23),
('Candarave', 23),
('Jorge Basadre', 23),
('Tarata', 23),
('Tumbes', 24),
('Contralmirante Villar', 24),
('Zarumilla', 24),
('Coronel Portillo', 25),
('Atalaya', 25),
('Padre Abad', 25),
('Purús', 25);

INSERT INTO Distrito (Distrito, id_provincia) VALUES
('Chachapoyas', 1),
('Asunción', 1),
('Balsas', 1),
('Cheto', 1),
('Chiliquin', 1),
('Chuquibamba', 1),
('Granada', 1),
('Huancas', 1),
('La Jalca', 1),
('Leimebamba', 1),
('Levanto', 1),
('Magdalena', 1),
('Mariscal Castilla', 1),
('Molinopampa', 1),
('Montevideo', 1),
('Olleros', 1),
('Quinjalca', 1),
('San Francisco de Daguas', 1),
('San Isidro de Maino', 1),
('Soloco', 1),
('Sonche', 1),
('Bagua', 1),
('Aramango', 1),
('Copallin', 1),
('El Parco', 1),
('Imaza', 1),
('La Peca', 1),
('Jumbilla', 1),
('Chisquilla', 1),
('Churuja', 1),
('Corosha', 1),
('Cuispes', 1),
('Florida', 1),
('Jazan', 1),
('Recta', 1),
('San Carlos', 1),
('Shipasbamba', 1),
('Valera', 1),
('Yambrasbamba', 1),
('Nieva', 1),
('El Cenepa', 1),
('Río Santiago', 1),
('Lamud', 1),
('Camporredondo', 1),
('Cocabamba', 1),
('Colcamar', 1),
('Conila', 1),
('Inguilpata', 1),
('Longuita', 1),
('Lonya Chico', 1),
('Luya', 1),
('Luya Viejo', 1),
('María', 1),
('Ocalli', 1),
('Ocumal', 1),
('Pisuquia', 1),
('Providencia', 1),
('San Cristóbal', 1),
('San Francisco de Yeso', 1),
('San Jerónimo', 1),
('San Juan de Lopecancha', 1),
('Santa Catalina', 1),
('Santo Tomas', 1),
('Tingo', 1),
('Trita', 1),
('San Nicolás', 1),
('Chirimoto', 1),
('Cochamal', 1),
('Huambo', 1),
('Limabamba', 1),
('Longar', 1),
('Mariscal Benavides', 1),
('Milpuc', 1),
('Omia', 1),
('Santa Rosa', 1),
('Totora', 1),
('Vista Alegre', 1),
('Bagua Grande', 1),
('Cajaruro', 1),
('Cumba', 1),
('El Milagro', 1),
('Jamalca', 1),
('Lonya Grande', 1),
('Yamon', 1),
('Huaraz', 2),
('Cochabamba', 2),
('Colcabamba', 2),
('Huanchay', 2),
('Independencia', 2),
('Jangas', 2),
('La Libertad', 2),
('Olleros', 2),
('Pampas Grande', 2),
('Pariacoto', 2),
('Pira', 2),
('Tarica', 2),
('Aija', 2),
('Coris', 2),
('Huacllan', 2),
('La Merced', 2),
('Succha', 2),
('Llamellin', 2),
('Aczo', 2),
('Chaccho', 2),
('Chingas', 2),
('Mirgas', 2),
('San Juan de Rontoy', 2),
('Chacas', 2),
('Acochaca', 2),
('Chiquian', 2),
('Abelardo Pardo Lezameta', 2),
('Antonio Raymondi', 2),
('Aquia', 2),
('Cajacay', 2),
('Canis', 2),
('Colquioc', 2),
('Huallanca', 2),
('Huasta', 2),
('Huayllacayan', 2),
('La Primavera', 2),
('Mangas', 2),
('Pacllon', 2),
('San Miguel de Corpanqui', 2),
('Ticllos', 2),
('Carhuaz', 2),
('Acopampa', 2),
('Amashca', 2),
('Anta', 2),
('Ataquero', 2),
('Marcara', 2),
('Pariahuanca', 2),
('San Miguel de Aco', 2),
('Shilla', 2),
('Tinco', 2),
('Yungar', 2),
('San Luis', 2),
('San Nicolás', 2),
('Yauya', 2),
('Casma', 2),
('Buena Vista Alta', 2),
('Comandante Noel', 2),
('Yautan', 2),
('Corongo', 2),
('Aco', 2),
('Bambas', 2),
('Cusca', 2),
('La Pampa', 2),
('Yanac', 2),
('Yupan', 2),
('Huari', 2),
('Anra', 2),
('Cajay', 2),
('Chavin de Huantar', 2),
('Huacachi', 2),
('Huacchis', 2),
('Huachis', 2),
('Huantar', 2),
('Masin', 2),
('Paucas', 2),
('Ponto', 2),
('Rahuapampa', 2),
('Rapayan', 2),
('San Marcos', 2),
('San Pedro de Chana', 2),
('Uco', 2),
('Huarmey', 2),
('Cochapeti', 2),
('Culebras', 2),
('Huayan', 2),
('Malvas', 2),
('Caraz', 2),
('Huallanca', 2),
('Huata', 2),
('Huaylas', 2),
('Mato', 2),
('Pamparomas', 2),
('Pueblo Libre', 2),
('Santa Cruz', 2),
('Santo Toribio', 2),
('Yuracmarca', 2),
('Piscobamba', 2),
('Casca', 2),
('Eleazar Guzmán Barron', 2),
('Fidel Olivas Escudero', 2),
('Llama', 2),
('Llumpa', 2),
('Lucma', 2),
('Musga', 2),
('Ocros', 2),
('Acas', 2),
('Cajamarquilla', 2),
('Carhuapampa', 2),
('Cochas', 2),
('Congas', 2),
('Llipa', 2),
('San Cristóbal de Rajan', 2),
('San Pedro', 2),
('Santiago de Chilcas', 2),
('Cabana', 2),
('Bolognesi', 2),
('Conchucos', 2),
('Huacaschuque', 2),
('Huandoval', 2),
('Lacabamba', 2),
('Llapo', 2),
('Pallasca', 2),
('Pampas', 2),
('Santa Rosa', 2),
('Tauca', 2),
('Pomabamba', 2),
('Huayllan', 2),
('Parobamba', 2),
('Quinuabamba', 2),
('Recuay', 2),
('Catac', 2),
('Cotaparaco', 2),
('Huayllapampa', 2),
('Llacllin', 2),
('Marca', 2),
('Pampas Chico', 2),
('Pararin', 2),
('Tapacocha', 2),
('Ticapampa', 2),
('Chimbote', 2),
('Cáceres del Perú', 2),
('Coishco', 2),
('Macate', 2),
('Moro', 2),
('Nepeña', 2),
('Samanco', 2),
('Santa', 2),
('Nuevo Chimbote', 2),
('Sihuas', 2),
('Acobamba', 2),
('Alfonso Ugarte', 2),
('Cashapampa', 2),
('Chingalpo', 2),
('Huayllabamba', 2),
('Quiches', 2),
('Ragash', 2),
('San Juan', 2),
('Sicsibamba', 2),
('Yungay', 2),
('Cascapara', 2),
('Mancos', 2),
('Matacoto', 2),
('Quillo', 2),
('Ranrahirca', 2),
('Shupluy', 2),
('Yanama', 2),
('Abancay', 3),
('Chacoche', 3),
('Circa', 3),
('Curahuasi', 3),
('Huanipaca', 3),
('Lambrama', 3),
('Pichirhua', 3),
('San Pedro de Cachora', 3),
('Tamburco', 3),
('Andahuaylas', 3),
('Andarapa', 3),
('Chiara', 3),
('Huancarama', 3),
('Huancaray', 3),
('Huayana', 3),
('Kishuara', 3),
('Pacobamba', 3),
('Pacucha', 3),
('Pampachiri', 3),
('Pomacocha', 3),
('San Antonio de Cachi', 3),
('San Jerónimo', 3),
('San Miguel de Chaccrampa', 3),
('Santa María de Chicmo', 3),
('Talavera', 3),
('Tumay Huaraca', 3),
('Turpo', 3),
('Kaquiabamba', 3),
('José María Arguedas', 3),
('Antabamba', 3),
('El Oro', 3),
('Huaquirca', 3),
('Juan Espinoza Medrano', 3),
('Oropesa', 3),
('Pachaconas', 3),
('Sabaino', 3),
('Chalhuanca', 3),
('Capaya', 3),
('Caraybamba', 3),
('Chapimarca', 3),
('Colcabamba', 3),
('Cotaruse', 3),
('Ihuayllo', 3),
('Justo Apu Sahuaraura', 3),
('Lucre', 3),
('Pocohuanca', 3),
('San Juan de Chacña', 3),
('Sañayca', 3),
('Soraya', 3),
('Tapairihua', 3),
('Tintay', 3),
('Toraya', 3),
('Yanaca', 3),
('Tambobamba', 3),
('Cotabambas', 3),
('Coyllurqui', 3),
('Haquira', 3),
('Mara', 3),
('Challhuahuacho', 3),
('Chincheros', 3),
('Anco_Huallo', 3),
('Cocharcas', 3),
('Huaccana', 3),
('Ocobamba', 3),
('Ongoy', 3),
('Uranmarca', 3),
('Ranracancha', 3),
('Rocchacc', 3),
('El Porvenir', 3),
('Los Chankas', 3),
('Chuquibambilla', 3),
('Curpahuasi', 3),
('Gamarra', 3),
('Huayllati', 3),
('Mamara', 3),
('Micaela Bastidas', 3),
('Pataypampa', 3),
('Progreso', 3),
('San Antonio', 3),
('Santa Rosa', 3),
('Turpay', 3),
('Vilcabamba', 3),
('Virundo', 3),
('Curasco', 3),
('Arequipa', 4),
('Alto Selva Alegre', 4),
('Cayma', 4),
('Cerro Colorado', 4),
('Characato', 4),
('Chiguata', 4),
('Jacobo Hunter', 4),
('La Joya', 4),
('Mariano Melgar', 4),
('Miraflores', 4),
('Mollebaya', 4),
('Paucarpata', 4),
('Pocsi', 4),
('Polobaya', 4),
('Quequeña', 4),
('Sabandia', 4),
('Sachaca', 4),
('San Juan de Siguas', 4),
('San Juan de Tarucani', 4),
('Santa Isabel de Siguas', 4),
('Santa Rita de Siguas', 4),
('Socabaya', 4),
('Tiabaya', 4),
('Uchumayo', 4),
('Vitor', 4),
('Yanahuara', 4),
('Yarabamba', 4),
('Yura', 4),
('José Luis Bustamante Y Rivero', 4),
('Camaná', 4),
('José María Quimper', 4),
('Mariano Nicolás Valcárcel', 4),
('Mariscal Cáceres', 4),
('Nicolás de Pierola', 4),
('Ocoña', 4),
('Quilca', 4),
('Samuel Pastor', 4),
('Caravelí', 4),
('Acarí', 4),
('Atico', 4),
('Atiquipa', 4),
('Bella Unión', 4),
('Cahuacho', 4),
('Chala', 4),
('Chaparra', 4),
('Huanuhuanu', 4),
('Jaqui', 4),
('Lomas', 4),
('Quicacha', 4),
('Yauca', 4),
('Aplao', 4),
('Andagua', 4),
('Ayo', 4),
('Chachas', 4),
('Chilcaymarca', 4),
('Choco', 4),
('Huancarqui', 4),
('Machaguay', 4),
('Orcopampa', 4),
('Pampacolca', 4),
('Tipan', 4),
('Uñon', 4),
('Uraca', 4),
('Viraco', 4),
('Chivay', 4),
('Achoma', 4),
('Cabanaconde', 4),
('Callalli', 4),
('Caylloma', 4),
('Coporaque', 4),
('Huambo', 4),
('Huanca', 4),
('Ichupampa', 4),
('Lari', 4),
('Lluta', 4),
('Maca', 4),
('Madrigal', 4),
('San Antonio de Chuca', 4),
('Sibayo', 4),
('Tapay', 4),
('Tisco', 4),
('Tuti', 4),
('Yanque', 4),
('Majes', 4),
('Chuquibamba', 4),
('Andaray', 4),
('Cayarani', 4),
('Chichas', 4),
('Iray', 4),
('Río Grande', 4),
('Salamanca', 4),
('Yanaquihua', 4),
('Mollendo', 4),
('Cocachacra', 4),
('Dean Valdivia', 4),
('Islay', 4),
('Mejia', 4),
('Punta de Bombón', 4),
('Cotahuasi', 4),
('Alca', 4),
('Charcana', 4),
('Huaynacotas', 4),
('Pampamarca', 4),
('Puyca', 4),
('Quechualla', 4),
('Sayla', 4),
('Tauria', 4),
('Tomepampa', 4),
('Toro', 4),
('Ayacucho', 5),
('Acocro', 5),
('Acos Vinchos', 5),
('Carmen Alto', 5),
('Chiara', 5),
('Ocros', 5),
('Pacaycasa', 5),
('Quinua', 5),
('San José de Ticllas', 5),
('San Juan Bautista', 5),
('Santiago de Pischa', 5),
('Socos', 5),
('Tambillo', 5),
('Vinchos', 5),
('Jesús Nazareno', 5),
('Andrés Avelino Cáceres Dorregaray', 5),
('Cangallo', 5),
('Chuschi', 5),
('Los Morochucos', 5),
('María Parado de Bellido', 5),
('Paras', 5),
('Totos', 5),
('Sancos', 5),
('Carapo', 5),
('Sacsamarca', 5),
('Santiago de Lucanamarca', 5),
('Huanta', 5),
('Ayahuanco', 5),
('Huamanguilla', 5),
('Iguain', 5),
('Luricocha', 5),
('Santillana', 5),
('Sivia', 5),
('Llochegua', 5),
('Canayre', 5),
('Uchuraccay', 5),
('Pucacolpa', 5),
('Chaca', 5),
('San Miguel', 5),
('Anco', 5),
('Ayna', 5),
('Chilcas', 5),
('Chungui', 5),
('Luis Carranza', 5),
('Santa Rosa', 5),
('Tambo', 5),
('Samugari', 5),
('Anchihuay', 5),
('Oronccoy', 5),
('Puquio', 5),
('Aucara', 5),
('Cabana', 5),
('Carmen Salcedo', 5),
('Chaviña', 5),
('Chipao', 5),
('Huac-Huas', 5),
('Laramate', 5),
('Leoncio Prado', 5),
('Llauta', 5),
('Lucanas', 5),
('Ocaña', 5),
('Otoca', 5),
('Saisa', 5),
('San Cristóbal', 5),
('San Juan', 5),
('San Pedro', 5),
('San Pedro de Palco', 5),
('Sancos', 5),
('Santa Ana de Huaycahuacho', 5),
('Santa Lucia', 5),
('Coracora', 5),
('Chumpi', 5),
('Coronel Castañeda', 5),
('Pacapausa', 5),
('Pullo', 5),
('Puyusca', 5),
('San Francisco de Ravacayco', 5),
('Upahuacho', 5),
('Pausa', 5),
('Colta', 5),
('Corculla', 5),
('Lampa', 5),
('Marcabamba', 5),
('Oyolo', 5),
('Pararca', 5),
('San Javier de Alpabamba', 5),
('San José de Ushua', 5),
('Sara Sara', 5),
('Querobamba', 5),
('Belén', 5),
('Chalcos', 5),
('Chilcayoc', 5),
('Huacaña', 5),
('Morcolla', 5),
('Paico', 5),
('San Pedro de Larcay', 5),
('San Salvador de Quije', 5),
('Santiago de Paucaray', 5),
('Soras', 5),
('Huancapi', 5),
('Alcamenca', 5),
('Apongo', 5),
('Asquipata', 5),
('Canaria', 5),
('Cayara', 5),
('Colca', 5),
('Huamanquiquia', 5),
('Huancaraylla', 5),
('Hualla', 5),
('Sarhua', 5),
('Vilcanchos', 5),
('Vilcas Huaman', 5),
('Accomarca', 5),
('Carhuanca', 5),
('Concepción', 5),
('Huambalpa', 5),
('Independencia', 5),
('Saurama', 5),
('Vischongo', 5),
('Cajamarca', 6),
('Asunción', 6),
('Chetilla', 6),
('Cospan', 6),
('Encañada', 6),
('Jesús', 6),
('Llacanora', 6),
('Los Baños del Inca', 6),
('Magdalena', 6),
('Matara', 6),
('Namora', 6),
('San Juan', 6),
('Cajabamba', 6),
('Cachachi', 6),
('Condebamba', 6),
('Sitacocha', 6),
('Celendín', 6),
('Chumuch', 6),
('Cortegana', 6),
('Huasmin', 6),
('Jorge Chávez', 6),
('José Gálvez', 6),
('Miguel Iglesias', 6),
('Oxamarca', 6),
('Sorochuco', 6),
('Sucre', 6),
('Utco', 6),
('La Libertad de Pallan', 6),
('Chota', 6),
('Anguia', 6),
('Chadin', 6),
('Chiguirip', 6),
('Chimban', 6),
('Choropampa', 6),
('Cochabamba', 6),
('Conchan', 6),
('Huambos', 6),
('Lajas', 6),
('Llama', 6),
('Miracosta', 6),
('Paccha', 6),
('Pion', 6),
('Querocoto', 6),
('San Juan de Licupis', 6),
('Tacabamba', 6),
('Tocmoche', 6),
('Chalamarca', 6),
('Contumaza', 6),
('Chilete', 6),
('Cupisnique', 6),
('Guzmango', 6),
('San Benito', 6),
('Santa Cruz de Toledo', 6),
('Tantarica', 6),
('Yonan', 6),
('Cutervo', 6),
('Callayuc', 6),
('Choros', 6),
('Cujillo', 6),
('La Ramada', 6),
('Pimpingos', 6),
('Querocotillo', 6),
('San Andrés de Cutervo', 6),
('San Juan de Cutervo', 6),
('San Luis de Lucma', 6),
('Santa Cruz', 6),
('Santo Domingo de la Capilla', 6),
('Santo Tomas', 6),
('Socota', 6),
('Toribio Casanova', 6),
('Bambamarca', 6),
('Chugur', 6),
('Hualgayoc', 6),
('Jaén', 6),
('Bellavista', 6),
('Chontali', 6),
('Colasay', 6),
('Huabal', 6),
('Las Pirias', 6),
('Pomahuaca', 6),
('Pucara', 6),
('Sallique', 6),
('San Felipe', 6),
('San José del Alto', 6),
('Santa Rosa', 6),
('San Ignacio', 6),
('Chirinos', 6),
('Huarango', 6),
('La Coipa', 6),
('Namballe', 6),
('San José de Lourdes', 6),
('Tabaconas', 6),
('Pedro Gálvez', 6),
('Chancay', 6),
('Eduardo Villanueva', 6),
('Gregorio Pita', 6),
('Ichocan', 6),
('José Manuel Quiroz', 6),
('José Sabogal', 6),
('San Miguel', 6),
('Bolívar', 6),
('Calquis', 6),
('Catilluc', 6),
('El Prado', 6),
('La Florida', 6),
('Llapa', 6),
('Nanchoc', 6),
('Niepos', 6),
('San Gregorio', 6),
('San Silvestre de Cochan', 6),
('Tongod', 6),
('Unión Agua Blanca', 6),
('San Pablo', 6),
('San Bernardino', 6),
('San Luis', 6),
('Tumbaden', 6),
('Santa Cruz', 6),
('Andabamba', 6),
('Catache', 6),
('Chancaybaños', 6),
('La Esperanza', 6),
('Ninabamba', 6),
('Pulan', 6),
('Saucepampa', 6),
('Sexi', 6),
('Uticyacu', 6),
('Yauyucan', 6),
('Callao', 7),
('Bellavista', 7),
('Carmen de la Legua Reynoso', 7),
('La Perla', 7),
('La Punta', 7),
('Ventanilla', 7),
('Mi Perú', 7),
('Cusco', 8),
('Ccorca', 8),
('Poroy', 8),
('San Jerónimo', 8),
('San Sebastian', 8),
('Santiago', 8),
('Saylla', 8),
('Wanchaq', 8),
('Acomayo', 8),
('Acopia', 8),
('Acos', 8),
('Mosoc Llacta', 8),
('Pomacanchi', 8),
('Rondocan', 8),
('Sangarara', 8),
('Anta', 8),
('Ancahuasi', 8),
('Cachimayo', 8),
('Chinchaypujio', 8),
('Huarocondo', 8),
('Limatambo', 8),
('Mollepata', 8),
('Pucyura', 8),
('Zurite', 8),
('Calca', 8),
('Coya', 8),
('Lamay', 8),
('Lares', 8),
('Pisac', 8),
('San Salvador', 8),
('Taray', 8),
('Yanatile', 8),
('Yanaoca', 8),
('Checca', 8),
('Kunturkanki', 8),
('Langui', 8),
('Layo', 8),
('Pampamarca', 8),
('Quehue', 8),
('Tupac Amaru', 8),
('Sicuani', 8),
('Checacupe', 8),
('Combapata', 8),
('Marangani', 8),
('Pitumarca', 8),
('San Pablo', 8),
('San Pedro', 8),
('Tinta', 8),
('Santo Tomas', 8),
('Capacmarca', 8),
('Chamaca', 8),
('Colquemarca', 8),
('Livitaca', 8),
('Llusco', 8),
('Quiñota', 8),
('Velille', 8),
('Espinar', 8),
('Condoroma', 8),
('Coporaque', 8),
('Ocoruro', 8),
('Pallpata', 8),
('Pichigua', 8),
('Suyckutambo', 8),
('Alto Pichigua', 8),
('Santa Ana', 8),
('Echarate', 8),
('Huayopata', 8),
('Maranura', 8),
('Ocobamba', 8),
('Quellouno', 8),
('Kimbiri', 8),
('Santa Teresa', 8),
('Vilcabamba', 8),
('Pichari', 8),
('Inkawasi', 8),
('Villa Virgen', 8),
('Villa Kintiarina', 8),
('Megantoni', 8),
('Paruro', 8),
('Accha', 8),
('Ccapi', 8),
('Colcha', 8),
('Huanoquite', 8),
('Omachaç', 8),
('Paccaritambo', 8),
('Pillpinto', 8),
('Yaurisque', 8),
('Paucartambo', 8),
('Caicay', 8),
('Challabamba', 8),
('Colquepata', 8),
('Huancarani', 8),
('Kosñipata', 8),
('Urcos', 8),
('Andahuaylillas', 8),
('Camanti', 8),
('Ccarhuayo', 8),
('Ccatca', 8),
('Cusipata', 8),
('Huaro', 8),
('Lucre', 8),
('Marcapata', 8),
('Ocongate', 8),
('Oropesa', 8),
('Quiquijana', 8),
('Urubamba', 8),
('Chinchero', 8),
('Huayllabamba', 8),
('Machupicchu', 8),
('Maras', 8),
('Ollantaytambo', 8),
('Yucay', 8),
('Huancavelica', 9),
('Acobambilla', 9),
('Acoria', 9),
('Conayca', 9),
('Cuenca', 9),
('Huachocolpa', 9),
('Huayllahuara', 9),
('Izcuchaca', 9),
('Laria', 9),
('Manta', 9),
('Mariscal Cáceres', 9),
('Moya', 9),
('Nuevo Occoro', 9),
('Palca', 9),
('Pilchaca', 9),
('Vilca', 9),
('Yauli', 9),
('Ascensión', 9),
('Huando', 9),
('Acobamba', 9),
('Andabamba', 9),
('Anta', 9),
('Caja', 9),
('Marcas', 9),
('Paucara', 9),
('Pomacocha', 9),
('Rosario', 9),
('Lircay', 9),
('Anchonga', 9),
('Callanmarca', 9),
('Ccochaccasa', 9),
('Chincho', 9),
('Congalla', 9),
('Huanca-Huanca', 9),
('Huayllay Grande', 9),
('Julcamarca', 9),
('San Antonio de Antaparco', 9),
('Santo Tomas de Pata', 9),
('Secclla', 9),
('Castrovirreyna', 9),
('Arma', 9),
('Aurahua', 9),
('Capillas', 9),
('Chupamarca', 9),
('Cocas', 9),
('Huachos', 9),
('Huamatambo', 9),
('Mollepampa', 9),
('San Juan', 9),
('Santa Ana', 9),
('Tantara', 9),
('Ticrapo', 9),
('Churcampa', 9),
('Anco', 9),
('Chinchihuasi', 9),
('El Carmen', 9),
('La Merced', 9),
('Locroja', 9),
('Paucarbamba', 9),
('San Miguel de Mayocc', 9),
('San Pedro de Coris', 9),
('Pachamarca', 9),
('Cosme', 9),
('Huaytara', 9),
('Ayavi', 9),
('Córdova', 9),
('Huayacundo Arma', 9),
('Laramarca', 9),
('Ocoyo', 9),
('Pilpichaca', 9),
('Querco', 9),
('Quito-Arma', 9),
('San Antonio de Cusicancha', 9),
('San Francisco de Sangayaico', 9),
('San Isidro', 9),
('Santiago de Chocorvos', 9),
('Santiago de Quirahuara', 9),
('Santo Domingo de Capillas', 9),
('Tambo', 9),
('Pampas', 9),
('Acostambo', 9),
('Acraquia', 9),
('Ahuaycha', 9),
('Colcabamba', 9),
('Daniel Hernández', 9),
('Huachocolpa', 9),
('Huaribamba', 9),
('Ñahuimpuquio', 9),
('Pazos', 9),
('Quishuar', 9),
('Salcabamba', 9),
('Salcahuasi', 9),
('San Marcos de Rocchac', 9),
('Surcubamba', 9),
('Tintay Puncu', 9),
('Quichuas', 9),
('Andaymarca', 9),
('Roble', 9),
('Pichos', 9),
('Santiago de Tucuma', 9),
('Huanuco', 10),
('Amarilis', 10),
('Chinchao', 10),
('Churubamba', 10),
('Margos', 10),
('Quisqui (Kichki)', 10),
('San Francisco de Cayran', 10),
('San Pedro de Chaulan', 10),
('Santa María del Valle', 10),
('Yarumayo', 10),
('Pillco Marca', 10),
('Yacus', 10),
('San Pablo de Pillao', 10),
('Ambo', 10),
('Cayna', 10),
('Colpas', 10),
('Conchamarca', 10),
('Huacar', 10),
('San Francisco', 10),
('San Rafael', 10),
('Tomay Kichwa', 10),
('La Unión', 10),
('Chuquis', 10),
('Marías', 10),
('Pachas', 10),
('Quivilla', 10),
('Ripan', 10),
('Shunqui', 10),
('Sillapata', 10),
('Yanas', 10),
('Huacaybamba', 10),
('Canchabamba', 10),
('Cochabamba', 10),
('Pinra', 10),
('Llata', 10),
('Arancay', 10),
('Chavín de Pariarca', 10),
('Jacas Grande', 10),
('Jircan', 10),
('Miraflores', 10),
('Monzón', 10),
('Punchao', 10),
('Puños', 10),
('Singa', 10),
('Tantamayo', 10),
('Rupa-Rupa', 10),
('Daniel Alomía Robles', 10),
('Hermílio Valdizan', 10),
('José Crespo y Castillo', 10),
('Luyando', 10),
('Mariano Damaso Beraun', 10),
('Pucayacu', 10),
('Castillo Grande', 10),
('Pueblo Nuevo', 10),
('Santo Domingo de Anda', 10),
('Huacrachuco', 10),
('Cholon', 10),
('San Buenaventura', 10),
('La Morada', 10),
('Santa Rosa de Alto Yanajanca', 10),
('Panao', 10),
('Chaglla', 10),
('Molino', 10),
('Umari', 10),
('Puerto Inca', 10),
('Codo del Pozuzo', 10),
('Honoria', 10),
('Tournavista', 10),
('Yuyapichis', 10),
('Jesús', 10),
('Baños', 10),
('Jivia', 10),
('Queropalca', 10),
('Rondos', 10),
('San Francisco de Asís', 10),
('San Miguel de Cauri', 10),
('Chavinillo', 10),
('Cahuac', 10),
('Chacabamba', 10),
('Aparicio Pomares', 10),
('Jacas Chico', 10),
('Obas', 10),
('Pampamarca', 10),
('Choras', 10),
('Ica', 11),
('La Tinguiña', 11),
('Los Aquijes', 11),
('Ocucaje', 11),
('Pachacutec', 11),
('Parcona', 11),
('Pueblo Nuevo', 11),
('Salas', 11),
('San José de Los Molinos', 11),
('San Juan Bautista', 11),
('Santiago', 11),
('Subtanjalla', 11),
('Tate', 11),
('Yauca del Rosario', 11),
('Chincha Alta', 11),
('Alto Laran', 11),
('Chavin', 11),
('Chincha Baja', 11),
('El Carmen', 11),
('Grocio Prado', 11),
('Pueblo Nuevo', 11),
('San Juan de Yanac', 11),
('San Pedro de Huacarpana', 11),
('Sunampe', 11),
('Tambo de Mora', 11),
('Nasca', 11),
('Changuillo', 11),
('El Ingenio', 11),
('Marcona', 11),
('Vista Alegre', 11),
('Palpa', 11),
('Llipata', 11),
('Río Grande', 11),
('Santa Cruz', 11),
('Tibillo', 11),
('Pisco', 11),
('Huancano', 11),
('Humay', 11),
('Independencia', 11),
('Paracas', 11),
('San Andrés', 11),
('San Clemente', 11),
('Tupac Amaru Inca', 11),
('Huancayo', 12),
('Carhuacallanga', 12),
('Chacapampa', 12),
('Chicche', 12),
('Chilca', 12),
('Chongos Alto', 12),
('Chupuro', 12),
('Colca', 12),
('Cullhuas', 12),
('El Tambo', 12),
('Huacrapuquio', 12),
('Hualhuas', 12),
('Huancan', 12),
('Huasicancha', 12),
('Huayucachi', 12),
('Ingenio', 12),
('Pariahuanca', 12),
('Pilcomayo', 12),
('Pucara', 12),
('Quichuay', 12),
('Quilcas', 12),
('San Agustín', 12),
('San Jerónimo de Tunan', 12),
('Saño', 12),
('Sapallanga', 12),
('Sicaya', 12),
('Santo Domingo de Acobamba', 12),
('Viques', 12),
('Concepción', 12),
('Aco', 12),
('Andamarca', 12),
('Chambara', 12),
('Cochas', 12),
('Comas', 12),
('Heroínas Toledo', 12),
('Manzanares', 12),
('Mariscal Castilla', 12),
('Matahuasi', 12),
('Mito', 12),
('Nueve de Julio', 12),
('Orcotuna', 12),
('San José de Quero', 12),
('Santa Rosa de Ocopa', 12),
('Chanchamayo', 12),
('Perene', 12),
('Pichanaqui', 12),
('San Luis de Shuaro', 12),
('San Ramón', 12),
('Vitoc', 12),
('Jauja', 12),
('Acolla', 12),
('Apata', 12),
('Ataura', 12),
('Canchayllo', 12),
('Curicaca', 12),
('El Mantaro', 12),
('Huamali', 12),
('Huaripampa', 12),
('Huertas', 12),
('Janjaillo', 12),
('Julcán', 12),
('Leonor Ordóñez', 12),
('Llocllapampa', 12),
('Marco', 12),
('Masma', 12),
('Masma Chicche', 12),
('Molinos', 12),
('Monobamba', 12),
('Muqui', 12),
('Muquiyauyo', 12),
('Paca', 12),
('Paccha', 12),
('Pancan', 12),
('Parco', 12),
('Pomacancha', 12),
('Ricran', 12),
('San Lorenzo', 12),
('San Pedro de Chunan', 12),
('Sausa', 12),
('Sincos', 12),
('Tunan Marca', 12),
('Yauli', 12),
('Yauyos', 12),
('Junin', 12),
('Carhuamayo', 12),
('Ondores', 12),
('Ulcumayo', 12),
('Satipo', 12),
('Coviriali', 12),
('Llaylla', 12),
('Mazamari', 12),
('Pampa Hermosa', 12),
('Pangoa', 12),
('Río Negro', 12),
('Río Tambo', 12),
('Vizcatan del Ene', 12),
('Tarma', 12),
('Acobamba', 12),
('Huaricolca', 12),
('Huasahuasi', 12),
('La Unión', 12),
('Palca', 12),
('Palcamayo', 12),
('San Pedro de Cajas', 12),
('Tapo', 12),
('La Oroya', 12),
('Chacapalpa', 12),
('Huay-Huay', 12),
('Marcapomacocha', 12),
('Morococha', 12),
('Paccha', 12),
('Santa Bárbara de Carhuacayan', 12),
('Santa Rosa de Sacco', 12),
('Suitucancha', 12),
('Yauli', 12),
('Chupaca', 12),
('Ahuac', 12),
('Chongos Bajo', 12),
('Huachac', 12),
('Huamancaca Chico', 12),
('San Juan de Iscos', 12),
('San Juan de Jarpa', 12),
('Tres de Diciembre', 12),
('Yanacancha', 12),
('Trujillo', 13),
('El Porvenir', 13),
('Florencia de Mora', 13),
('Huanchaco', 13),
('La Esperanza', 13),
('Laredo', 13),
('Moche', 13),
('Poroto', 13),
('Salaverry', 13),
('Simbal', 13),
('Victor Larco Herrera', 13),
('Ascope', 13),
('Chicama', 13),
('Chocope', 13),
('Magdalena de Cao', 13),
('Paijan', 13),
('Rázuri', 13),
('Santiago de Cao', 13),
('Casa Grande', 13),
('Bolívar', 13),
('Bambamarca', 13),
('Condormarca', 13),
('Longotea', 13),
('Uchumarca', 13),
('Ucuncha', 13),
('Chepen', 13),
('Pacanga', 13),
('Pueblo Nuevo', 13),
('Julcan', 13),
('Calamarca', 13),
('Carabamba', 13),
('Huaso', 13),
('Otuzco', 13),
('Agallpampa', 13),
('Charat', 13),
('Huaranchal', 13),
('La Cuesta', 13),
('Mache', 13),
('Paranday', 13),
('Salpo', 13),
('Sinsicap', 13),
('Usquil', 13),
('San Pedro de Lloc', 13),
('Guadalupe', 13),
('Jequetepeque', 13),
('Pacasmayo', 13),
('San José', 13),
('Tayabamba', 13),
('Buldibuyo', 13),
('Chillia', 13),
('Huancaspata', 13),
('Huaylillas', 13),
('Huayo', 13),
('Ongon', 13),
('Parcoy', 13),
('Pataz', 13),
('Pias', 13),
('Santiago de Challas', 13),
('Taurija', 13),
('Urpay', 13),
('Huamachuco', 13),
('Chugay', 13),
('Cochorco', 13),
('Curgos', 13),
('Marcabal', 13),
('Sanagoran', 13),
('Sarin', 13),
('Sartimbamba', 13),
('Santiago de Chuco', 13),
('Angasmarca', 13),
('Cachicadan', 13),
('Mollebamba', 13),
('Mollepata', 13),
('Quiruvilca', 13),
('Santa Cruz de Chuca', 13),
('Sitabamba', 13),
('Cascas', 13),
('Lucma', 13),
('Marmot', 13),
('Sayapullo', 13),
('Viru', 13),
('Chao', 13),
('Guadalupito', 13),
('Chiclayo', 14),
('Chongoyape', 14),
('Eten', 14),
('Eten Puerto', 14),
('José Leonardo Ortiz', 14),
('La Victoria', 14),
('Lagunas', 14),
('Monsefu', 14),
('Nueva Arica', 14),
('Oyotun', 14),
('Picsi', 14),
('Pimentel', 14),
('Reque', 14),
('Santa Rosa', 14),
('Saña', 14),
('Cayalti', 14),
('Patapo', 14),
('Pomalca', 14),
('Pucala', 14),
('Tuman', 14),
('Ferreñafe', 14),
('Cañaris', 14),
('Incahuasi', 14),
('Manuel Antonio Mesones Muro', 14),
('Pitipo', 14),
('Pueblo Nuevo', 14),
('Lambayeque', 14),
('Chochope', 14),
('Illimo', 14),
('Jayanca', 14),
('Mochumi', 14),
('Morrope', 14),
('Motupe', 14),
('Olmos', 14),
('Pacora', 14),
('Salas', 14),
('San José', 14),
('Tucume', 14),
('Lima', 15),
('Ancón', 15),
('Ate', 15),
('Barranco', 15),
('Breña', 15),
('Carabayllo', 15),
('Chaclacayo', 15),
('Chorrillos', 15),
('Cieneguilla', 15),
('Comas', 15),
('El Agustino', 15),
('Independencia', 15),
('Jesús María', 15),
('La Molina', 15),
('La Victoria', 15),
('Lince', 15),
('Los Olivos', 15),
('Lurigancho', 15),
('Lurin', 15),
('Magdalena del Mar', 15),
('Pueblo Libre', 15),
('Miraflores', 15),
('Pachacamac', 15),
('Pucusana', 15),
('Puente Piedra', 15),
('Punta Hermosa', 15),
('Punta Negra', 15),
('Rímac', 15),
('San Bartolo', 15),
('San Borja', 15),
('San Isidro', 15),
('San Juan de Lurigancho', 15),
('San Juan de Miraflores', 15),
('San Luis', 15),
('San Martín de Porres', 15),
('San Miguel', 15),
('Santa Anita', 15),
('Santa María del Mar', 15),
('Santa Rosa', 15),
('Santiago de Surco', 15),
('Surquillo', 15),
('Villa El Salvador', 15),
('Villa María del Triunfo', 15),
('Barranca', 15),
('Paramonga', 15),
('Pativilca', 15),
('Supe', 15),
('Supe Puerto', 15),
('Cajatambo', 15),
('Copa', 15),
('Gorgor', 15),
('Huancapon', 15),
('Manas', 15),
('Canta', 15),
('Arahuay', 15),
('Huamantanga', 15),
('Huaros', 15),
('Lachaqui', 15),
('San Buenaventura', 15),
('Santa Rosa de Quives', 15),
('San Vicente de Cañete', 15),
('Asia', 15),
('Calango', 15),
('Cerro Azul', 15),
('Chilca', 15),
('Coayllo', 15),
('Imperial', 15),
('Lunahuana', 15),
('Mala', 15),
('Nuevo Imperial', 15),
('Pacaran', 15),
('Quilmana', 15),
('San Antonio', 15),
('San Luis', 15),
('Santa Cruz de Flores', 15),
('Zúñiga', 15),
('Huaral', 15),
('Atavillos Alto', 15),
('Atavillos Bajo', 15),
('Aucallama', 15),
('Chancay', 15),
('Ihuari', 15),
('Lampian', 15),
('Pacaraos', 15),
('San Miguel de Acos', 15),
('Santa Cruz de Andamarca', 15),
('Sumbilca', 15),
('Veintisiete de Noviembre', 15),
('Matucana', 15),
('Antioquia', 15),
('Callahuanca', 15),
('Carampoma', 15),
('Chicla', 15),
('Cuenca', 15),
('Huachupampa', 15),
('Huanza', 15),
('Huarochiri', 15),
('Lahuaytambo', 15),
('Langa', 15),
('Laraos', 15),
('Mariatana', 15),
('Ricardo Palma', 15),
('San Andrés de Tupicocha', 15),
('San Antonio', 15),
('San Bartolomé', 15),
('San Damian', 15),
('San Juan de Iris', 15),
('San Juan de Tantaranche', 15),
('San Lorenzo de Quinti', 15),
('San Mateo', 15),
('San Mateo de Otao', 15),
('San Pedro de Casta', 15),
('San Pedro de Huancayre', 15),
('Sangallaya', 15),
('Santa Cruz de Cocachacra', 15),
('Santa Eulalia', 15),
('Santiago de Anchucaya', 15),
('Santiago de Tuna', 15),
('Santo Domingo de Los Olleros', 15),
('Surco', 15),
('Huacho', 15),
('Ambar', 15),
('Caleta de Carquin', 15),
('Checras', 15),
('Hualmay', 15),
('Huaura', 15),
('Leoncio Prado', 15),
('Paccho', 15),
('Santa Leonor', 15),
('Santa María', 15),
('Sayan', 15),
('Vegueta', 15),
('Oyon', 15),
('Andajes', 15),
('Caujul', 15),
('Cochamarca', 15),
('Navan', 15),
('Pachangara', 15),
('Yauyos', 15),
('Alis', 15),
('Allauca', 15),
('Ayaviri', 15),
('Azángaro', 15),
('Cacra', 15),
('Carania', 15),
('Catahuasi', 15),
('Chocos', 15),
('Cochas', 15),
('Colonia', 15),
('Hongos', 15),
('Huampara', 15),
('Huancaya', 15),
('Huangascar', 15),
('Huantan', 15),
('Huañec', 15),
('Laraos', 15),
('Lincha', 15),
('Madean', 15),
('Miraflores', 15),
('Omas', 15),
('Putinza', 15),
('Quinches', 15),
('Quinocay', 15),
('San Joaquín', 15),
('San Pedro de Pilas', 15),
('Tanta', 15),
('Tauripampa', 15),
('Tomas', 15),
('Tupe', 15),
('Viñac', 15),
('Vitis', 15),
('Iquitos', 16),
('Alto Nanay', 16),
('Fernando Lores', 16),
('Indiana', 16),
('Las Amazonas', 16),
('Mazan', 16),
('Napo', 16),
('Punchana', 16),
('Torres Causana', 16),
('Belén', 16),
('San Juan Bautista', 16),
('Yurimaguas', 16),
('Balsapuerto', 16),
('Jeberos', 16),
('Lagunas', 16),
('Santa Cruz', 16),
('Teniente Cesar López Rojas', 16),
('Nauta', 16),
('Parinari', 16),
('Tigre', 16),
('Trompeteros', 16),
('Urarinas', 16),
('Ramón Castilla', 16),
('Pebas', 16),
('Yavari', 16),
('San Pablo', 16),
('Requena', 16),
('Alto Tapiche', 16),
('Capelo', 16),
('Emilio San Martín', 16),
('Maquia', 16),
('Puinahua', 16),
('Saquena', 16),
('Soplin', 16),
('Tapiche', 16),
('Jenaro Herrera', 16),
('Yaquerana', 16),
('Contamana', 16),
('Inahuaya', 16),
('Padre Márquez', 16),
('Pampa Hermosa', 16),
('Sarayacu', 16),
('Vargas Guerra', 16),
('Barranca', 16),
('Cahuapanas', 16),
('Manseriche', 16),
('Morona', 16),
('Pastaza', 16),
('Andoas', 16),
('Putumayo', 16),
('Rosa Panduro', 16),
('Teniente Manuel Clavero', 16),
('Yaguas', 16),
('Tambopata', 17),
('Inambari', 17),
('Las Piedras', 17),
('Laberinto', 17),
('Manu', 17),
('Fitzcarrald', 17),
('Madre de Dios', 17),
('Huepetuhe', 17),
('Iñapari', 17),
('Iberia', 17),
('Tahuamanu', 17),
('Moquegua', 18),
('Carumas', 18),
('Cuchumbaya', 18),
('Samegua', 18),
('San Cristóbal', 18),
('Torata', 18),
('Omate', 18),
('Chojata', 18),
('Coalaque', 18),
('Ichuña', 18),
('La Capilla', 18),
('Lloque', 18),
('Matalaque', 18),
('Puquina', 18),
('Quinistaquillas', 18),
('Ubinas', 18),
('Yunga', 18),
('Ilo', 18),
('El Algarrobal', 18),
('Pacocha', 18),
('Chaupimarca', 19),
('Huachon', 19),
('Huariaca', 19),
('Huayllay', 19),
('Ninacaca', 19),
('Pallanchacra', 19),
('Paucartambo', 19),
('San Francisco de Asís de Yarusyacan', 19),
('Simon Bolívar', 19),
('Ticlacayan', 19),
('Tinyahuarco', 19),
('Vicco', 19),
('Yanacancha', 19),
('Yanahuanca', 19),
('Chacayan', 19),
('Goyllarisquizga', 19),
('Paucar', 19),
('San Pedro de Pillao', 19),
('Santa Ana de Tusi', 19),
('Tapuc', 19),
('Vilcabamba', 19),
('Oxapampa', 19),
('Chontabamba', 19),
('Huancabamba', 19),
('Palcazu', 19),
('Pozuzo', 19),
('Puerto Bermúdez', 19),
('Villa Rica', 19),
('Constitución', 19),
('Piura', 20),
('Castilla', 20),
('Catacaos', 20),
('Cura Mori', 20),
('El Tallan', 20),
('La Arena', 20),
('La Unión', 20),
('Las Lomas', 20),
('Tambo Grande', 20),
('Veintiseis de Octubre', 20),
('Ayabaca', 20),
('Frias', 20),
('Jilili', 20),
('Lagunas', 20),
('Montero', 20),
('Pacaipampa', 20),
('Paimas', 20),
('Sapillica', 20),
('Sicchez', 20),
('Suyo', 20),
('Huancabamba', 20),
('Canchaque', 20),
('El Carmen de la Frontera', 20),
('Huarmaca', 20),
('Lalaquiz', 20),
('San Miguel de El Faique', 20),
('Sondor', 20),
('Sondorillo', 20),
('Chulucanas', 20),
('Buenos Aires', 20),
('Chalaco', 20),
('La Matanza', 20),
('Morropon', 20),
('Salitral', 20),
('San Juan de Bigote', 20),
('Santa Catalina de Mossa', 20),
('Santo Domingo', 20),
('Yamango', 20),
('Paita', 20),
('Amotape', 20),
('Arenal', 20),
('Colan', 20),
('La Huaca', 20),
('Tamarindo', 20),
('Vichayal', 20),
('Sullana', 20),
('Bellavista', 20),
('Ignacio Escudero', 20),
('Lancones', 20),
('Marcavelica', 20),
('Miguel Checa', 20),
('Querecotillo', 20),
('Salitral', 20),
('Pariñas', 20),
('El Alto', 20),
('La Brea', 20),
('Lobitos', 20),
('Los Organos', 20),
('Mancora', 20),
('Sechura', 20),
('Bellavista de la Unión', 20),
('Bernal', 20),
('Cristo Nos Valga', 20),
('Vice', 20),
('Rinconada Llicuar', 20),
('Puno', 21),
('Acora', 21),
('Amantani', 21),
('Atuncolla', 21),
('Capachica', 21),
('Chucuito', 21),
('Coata', 21),
('Huata', 21),
('Mañazo', 21),
('Paucarcolla', 21),
('Pichacani', 21),
('Plateria', 21),
('San Antonio', 21),
('Tiquillaca', 21),
('Vilque', 21),
('Azángaro', 21),
('Achaya', 21),
('Arapa', 21),
('Asillo', 21),
('Caminaca', 21),
('Chupa', 21),
('José Domingo Choquehuanca', 21),
('Muñani', 21),
('Potoni', 21),
('Saman', 21),
('San Anton', 21),
('San José', 21),
('San Juan de Salinas', 21),
('Santiago de Pupuja', 21),
('Tirapata', 21),
('Macusani', 21),
('Ajoyani', 21),
('Ayapata', 21),
('Coasa', 21),
('Corani', 21),
('Crucero', 21),
('Ituata', 21),
('Ollachea', 21),
('San Gaban', 21),
('Usicayos', 21),
('Juli', 21),
('Desaguadero', 21),
('Huacullani', 21),
('Kelluyo', 21),
('Pisacoma', 21),
('Pomata', 21),
('Zepita', 21),
('Ilave', 21),
('Capazo', 21),
('Pilcuyo', 21),
('Santa Rosa', 21),
('Conduriri', 21),
('Huancane', 21),
('Cojata', 21),
('Huatasani', 21),
('Inchupalla', 21),
('Pusi', 21),
('Rosaspata', 21),
('Taraco', 21),
('Vilque Chico', 21),
('Lampa', 21),
('Cabanilla', 21),
('Calapuja', 21),
('Nicasio', 21),
('Ocuviri', 21),
('Palca', 21),
('Paratia', 21),
('Pucara', 21),
('Santa Lucia', 21),
('Vilavila', 21),
('Ayaviri', 21),
('Antauta', 21),
('Cupi', 21),
('Llalli', 21),
('Macari', 21),
('Nuñoa', 21),
('Orurillo', 21),
('Santa Rosa', 21),
('Umachiri', 21),
('Moho', 21),
('Conima', 21),
('Huayrapata', 21),
('Tilali', 21),
('Putina', 21),
('Ananea', 21),
('Pedro Vilca Apaza', 21),
('Quilcapuncu', 21),
('Sina', 21),
('Juliaca', 21),
('Cabana', 21),
('Cabanillas', 21),
('Caracoto', 21),
('San Miguel', 21),
('Sandia', 21),
('Cuyocuyo', 21),
('Limbani', 21),
('Patambuco', 21),
('Phara', 21),
('Quiaca', 21),
('San Juan del Oro', 21),
('Yanahuaya', 21),
('Alto Inambari', 21),
('San Pedro de Putina Punco', 21),
('Yunguyo', 21),
('Anapia', 21),
('Copani', 21),
('Cuturapi', 21),
('Ollaraya', 21),
('Tinicachi', 21),
('Unicachi', 21),
('Moyobamba', 22),
('Calzada', 22),
('Habana', 22),
('Jepelacio', 22),
('Soritor', 22),
('Yantalo', 22),
('Bellavista', 22),
('Alto Biavo', 22),
('Bajo Biavo', 22),
('Huallaga', 22),
('San Pablo', 22),
('San Rafael', 22),
('San José de Sisa', 22),
('Agua Blanca', 22),
('San Martín', 22),
('Santa Rosa', 22),
('Shatoja', 22),
('Saposoa', 22),
('Alto Saposoa', 22),
('El Eslabón', 22),
('Piscoyacu', 22),
('Sacanche', 22),
('Tingo de Saposoa', 22),
('Lamas', 22),
('Alonso de Alvarado', 22),
('Barranquita', 22),
('Caynarachi', 22),
('Cuñumbuqui', 22),
('Pinto Recodo', 22),
('Rumisapa', 22),
('San Roque de Cumbaza', 22),
('Shanao', 22),
('Tabalosos', 22),
('Zapatero', 22),
('Juanjuí', 22),
('Campanilla', 22),
('Huicungo', 22),
('Pachiza', 22),
('Pajarillo', 22),
('Picota', 22),
('Buenos Aires', 22),
('Caspisapa', 22),
('Pilluana', 22),
('Pucacaca', 22),
('San Cristóbal', 22),
('San Hilarión', 22),
('Shamboyacu', 22),
('Tingo de Ponasa', 22),
('Tres Unidos', 22),
('Rioja', 22),
('Awajun', 22),
('Elías Soplin Vargas', 22),
('Nueva Cajamarca', 22),
('Pardo Miguel', 22),
('Posic', 22),
('San Fernando', 22),
('Yorongos', 22),
('Yuracyacu', 22),
('Tarapoto', 22),
('Alberto Leveau', 22),
('Cacatachi', 22),
('Chazuta', 22),
('Chipurana', 22),
('El Porvenir', 22),
('Huimbayoc', 22),
('Juan Guerra', 22),
('La Banda de Shilcayo', 22),
('Morales', 22),
('Papaplaya', 22),
('San Antonio', 22),
('Sauce', 22),
('Shapaja', 22),
('Tocache', 22),
('Nuevo Progreso', 22),
('Polvora', 22),
('Shunte', 22),
('Uchiza', 22),
('Tacna', 23),
('Alto de la Alianza', 23),
('Calana', 23),
('Ciudad Nueva', 23),
('Inclan', 23),
('Pachia', 23),
('Palca', 23),
('Pocollay', 23),
('Sama', 23),
('Coronel Gregorio Albarracín Lanchipa', 23),
('La Yarada los Palos', 23),
('Candarave', 23),
('Cairani', 23),
('Camilaca', 23),
('Curibaya', 23),
('Huanuara', 23),
('Quilahuani', 23),
('Locumba', 23),
('Ilabaya', 23),
('Ite', 23),
('Tarata', 23),
('Héroes Albarracín', 23),
('Estique', 23),
('Estique-Pampa', 23),
('Sitajara', 23),
('Susapaya', 23),
('Tarucachi', 23),
('Ticaco', 23),
('Tumbes', 24),
('Corrales', 24),
('La Cruz', 24),
('Pampas de Hospital', 24),
('San Jacinto', 24),
('San Juan de la Virgen', 24),
('Zorritos', 24),
('Casitas', 24),
('Canoas de Punta Sal', 24),
('Zarumilla', 24),
('Aguas Verdes', 24),
('Matapalo', 24),
('Papayal', 24),
('Calleria', 25),
('Campoverde', 25),
('Iparia', 25),
('Masisea', 25),
('Yarinacocha', 25),
('Nueva Requena', 25),
('Manantay', 25),
('Raymondi', 25),
('Sepahua', 25),
('Tahuania', 25),
('Yurua', 25),
('Padre Abad', 25),
('Irazola', 25),
('Curimana', 25),
('Neshuya', 25),
('Alexander Von Humboldt', 25),
('Purus', 25);

INSERT INTO EstadoCivil(EstadoCivil) VALUES
("SOLTERO"),
("CASADO");

INSERT INTO NivelSocioeco(NivelSocioeco) VALUES
("POBRE"),
("POBRE EXTREMO"),
("NO POBRE");

INSERT INTO TipoDocumento(tipo) VALUES
("DNI"),
("CEDULA"),
("CARNET DE EXTRANJERIA");

INSERT INTO TipoComprobante(TipoComprobante) VALUES
("BOLETA"),
("FACTURA");

INSERT INTO Categoria(Categoria) values
("MEDICAMENTOS"),
("SALUD"),
("ARTICULOS MEDICOS");

INSERT INTO EstadoProducto(EstadoProducto) VALUES
("DISPONIBLE"),
("TERMINADO");

INSERT INTO EstadoCliente(EstadoCliente) VALUES
("HABIDO"),
("NO HABIDO");

INSERT INTO EstadoVendedor(EstadoVendedor) VALUES
("HABIDO"),
("NO HABIDO");